title: goitse morena
description: A minimal blog page template

url: https://goitsemorena.cf
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: goitsemo
  twitter: goitsemorena
  facebook: goitsemorena
  email: goitsemorena@outlook.com
  linkedin: goitsemorena

